name: CI/CD OnibiExchange

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build app JAR with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t onibiexchange:latest .

      - name: Save Docker image
        run: docker save onibiexchange:latest -o onibiexchange.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: onibiexchange
          path: onibiexchange.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: onibiexchange
          path: .

      - name: Copy image to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "onibiexchange.tar"
          target: "~/onibiexchange"

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/onibiexchange
            docker load < onibiexchange.tar
            docker-compose down
            docker-compose up -d --build
